// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6dsusnECOfPmLCnRFyCfml9N0ng25GM',
    appId: '1:386891168137:web:77916e1851f2ce5a314958',
    messagingSenderId: '386891168137',
    projectId: 'tintuc-a0ba2',
    authDomain: 'tintuc-a0ba2.firebaseapp.com',
    databaseURL: 'https://tintuc-a0ba2-default-rtdb.firebaseio.com',
    storageBucket: 'tintuc-a0ba2.appspot.com',
    measurementId: 'G-EZB2449TGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhuGKCVaGv6r27AjSmpT2Bl43E5qzkJs',
    appId: '1:386891168137:android:e7cc0da67a08f809314958',
    messagingSenderId: '386891168137',
    projectId: 'tintuc-a0ba2',
    databaseURL: 'https://tintuc-a0ba2-default-rtdb.firebaseio.com',
    storageBucket: 'tintuc-a0ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCamUAnoUFhE_8fOjtN5rHdaDkCgfjZY5A',
    appId: '1:386891168137:ios:978ff18ddfc067d0314958',
    messagingSenderId: '386891168137',
    projectId: 'tintuc-a0ba2',
    databaseURL: 'https://tintuc-a0ba2-default-rtdb.firebaseio.com',
    storageBucket: 'tintuc-a0ba2.appspot.com',
    androidClientId: '386891168137-bv01gm6mag4ou5q342ga9pj5e489j19e.apps.googleusercontent.com',
    iosClientId: '386891168137-6fs0g2u4anrt6sm089t6k1pmqitc69ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.tintuc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCamUAnoUFhE_8fOjtN5rHdaDkCgfjZY5A',
    appId: '1:386891168137:ios:9afbed10ca39ab33314958',
    messagingSenderId: '386891168137',
    projectId: 'tintuc-a0ba2',
    databaseURL: 'https://tintuc-a0ba2-default-rtdb.firebaseio.com',
    storageBucket: 'tintuc-a0ba2.appspot.com',
    androidClientId: '386891168137-bv01gm6mag4ou5q342ga9pj5e489j19e.apps.googleusercontent.com',
    iosClientId: '386891168137-1ffkad4cfq38sp1dhu8parsnl63t763o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tintuc.RunnerTests',
  );
}
